<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Rcn extends Model
{
    // Definir el nombre de la tabla explícitamente si no sigue las convenciones de Laravel
    protected $table = 'ACMROI';

    // Definir la clave primaria de la tabla
    protected $primaryKey = ['CNCIASID', 'ACMROITDOC', 'ACMROINDOC', 'CNTDOCID', 'ACMROIDOC', 'ACMROILIN'];

    // Si la clave primaria no es un entero autoincremental
    public $incrementing = false;

    // Desactivar timestamps si la tabla no tiene created_at y updated_at
    public $timestamps = false;

    // Definir los tipos de datos para las claves primarias compuestas
    protected $keyType = 'decimal';

    // Especificar los campos que pueden ser asignados en masa
    protected $fillable = [
        'CNCIASID', 'ACMROITDOC', 'ACMROINDOC', 'CNTDOCID', 'ACMROIDOC', 'ACMROILIN',
        'ACMROINPED', 'ACMROIFREC', 'CNCDIRID', 'ACMROIDEM', 'INALMNID', 'ACMVOIAOD', 'CNCMNMID',
        'ACMROIFDOC', 'ACMROIFCEP', 'ACMROIFREQ', 'ACMROIFTRN', 'ACMROIFCNT', 'ACMVOIPR',
        'ACMVOIMOD', 'ACMVOITCMB', 'ACMVOIFOB', 'INPRODID', 'ACMROIDSC', 'ACMROIUMT', 'ACMROIIVA',
        'ACMROIQT', 'ACMROIQTTR', 'ACMROINP', 'ACMROINM', 'ACMROINI', 'ACMROING', 'ACMROIFP',
        'ACMROIFM', 'ACMROIFI', 'ACMROIFG', 'ACACTLID', 'ACACSGID', 'ACACANID', 'ACMROIDOC2',
        'ACMROIDOI2', 'ACMROIDOC3', 'ACMROIDOI3', 'ACMROISFJ', 'ACMROIFPR', 'ACMROIFDC',
        'ACMROIFVN', 'ACMROILOTE', 'ACMROIUB1', 'ACMROIUB2', 'ACMROIUB3', 'ACMROIUB4',
        'ACMROICXP', 'ACMROIPAD1', 'ACMROIPFC1', 'ACMROIPAD2', 'ACMROIPFC2', 'ACMROIPAD3',
        'ACMROIPFC3', 'ACMROITDP1', 'ACMROIDCP1', 'ACMROICIP1', 'ACMROIOBS', 'ACMROIYY',
        'ACMROICTGOID', 'ACMROICTGODSC', 'ACMROIACTSID', 'ACMROIACTSDSC', 'ACAUTRID',
        'ACMROILDP1', 'ACMROIDOI4', 'ACMROIDOC4', 'ACMROIQTYC', 'ACMROIQTYQ', 'ACMROIQTYT',
        'ACMROIREF', 'ACMROITREF', 'ACACCRLT', 'ACMROINP2', 'ACMROINM2', 'ACMROINI2', 'ACMROING2',
        'ACMROIFP2', 'ACMROIFM2', 'ACMROIFI2', 'ACMROIFG2', 'ACMROIACCT', 'ACMROIFOC', 'ACMROICCAD',
        'ACMROIRET', 'CGCOCSID', 'ACRCOICD01ID', 'ACRCOICD02ID', 'ACRCOICD03ID', 'ACRCOICD04ID',
        'ACRCOICD05ID', 'ACRCOICD06ID', 'ACRCOICD07ID', 'ACRCOICD08ID', 'ACRCOICD09ID',
        'ACRCOICD10ID', 'ACRCOICD11ID', 'ACRCOICD12ID', 'ACRCOICD13ID', 'ACRCOICD14ID',
        'ACRCOICD15ID', 'ACRCOICD16ID', 'ACRCOICD17ID', 'ACRCOICD18ID', 'ACRCOICD19ID',
        'ACRCOICD20ID', 'CGUNNGID', 'ACMROIUGPT', 'ACMROIFGPT', 'ACMROICEP', 'ACMROIMEP',
        'FCSPREID', 'ACMROIBGP', 'ACMROIEMTID', 'ACMROIEMTDSC', 'ACMROICHOF', 'ACMROIGUIA',
        'ACMROIPLAC', 'ACMROIFENT', 'ACMROIFSAL', 'ACMROIRUTA', 'ACMROINECO', 'ACMROIOBST',
        'ACMROIQTO', 'ACRCOICGJR01ID', 'ACRCOICGJR02ID', 'ACRCOICGJR03ID', 'ACRCOICGJR04ID',
        'ACRCOICGJR05ID', 'ACRCOICGJR06ID', 'ACRCOICGJR07ID', 'ACRCOICGJR08ID', 'ACRCOICGJR09ID',
        'ACRCOICGJR10ID', 'ACMROICAN', 'ACMROIUSRC', 'ACMROIFECC', 'ACMROITDOCCAN', 'ACMROINDOCCAN',
        'ACMROIVOLU', 'ACMROIPESOU', 'ACMROIVOLT', 'ACMROIPESOT', 'ACMROIABC'
    ];
}
